name: Error Monitor and Auto-Fix

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  check-and-fix:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Get workflow run logs
        id: get-logs
        uses: actions/github-script@v7
        with:
          script: |
            const run_id = context.payload.workflow_run.id;
            const { data: run } = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run_id
            });
            
            // Get job logs
            const { data: jobs } = await github.rest.actions.listJobsForWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: run_id
            });
            
            let errorDetails = '';
            for (const job of jobs.jobs) {
              if (job.conclusion === 'failure') {
                errorDetails += `Job: ${job.name}\n`;
                errorDetails += `Status: ${job.status}\n`;
                errorDetails += `Conclusion: ${job.conclusion}\n\n`;
              }
            }
            
            return {
              run_url: run.html_url,
              error_details: errorDetails,
              commit_sha: run.head_sha,
              commit_message: run.head_commit.message
            };
            
      - name: Create Issue
        id: create-issue
        uses: actions/github-script@v7
        with:
          script: |
            const logs = ${{ steps.get-logs.outputs.result }};
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🚨 Deployment Failed: ${new Date().toISOString().split('T')[0]}`,
              body: `## Deployment Error Report
            
            The deployment workflow failed. Here are the details:
            
            **Workflow Run:** ${logs.run_url}
            **Commit:** ${logs.commit_sha}
            **Commit Message:** ${logs.commit_message}
            
            ### Error Details
            \`\`\`
            ${logs.error_details}
            \`\`\`
            
            ### Automated Fix Attempt
            This issue was automatically created. An automated fix will be attempted.
            
            ---
            *Generated by Error Monitor workflow*`,
              labels: ['bug', 'deployment', 'automated']
            });
            
            return issue.data.number;
            
      - name: Analyze and Fix Common Issues
        id: auto-fix
        run: |
          # Common fixes for deployment issues
          FIXED=false
          FIX_MESSAGE=""
          
          # Check if .nojekyll exists
          if [ ! -f .nojekyll ]; then
            touch .nojekyll
            FIXED=true
            FIX_MESSAGE="Added missing .nojekyll file"
          fi
          
          # Check if GitHub Pages workflow permissions
          if grep -q "pages: write" .github/workflows/deploy.yml; then
            echo "Pages permission already set"
          else
            # Add pages permission if missing
            sed -i '/permissions:/a\  pages: write' .github/workflows/deploy.yml
            FIXED=true
            FIX_MESSAGE="${FIX_MESSAGE}\nAdded pages write permission"
          fi
          
          # Fix common module path issues
          if grep -q "from './src/" index.html; then
            sed -i "s|from '\./src/|from './src/|g" index.html
            FIXED=true
            FIX_MESSAGE="${FIX_MESSAGE}\nFixed module import paths"
          fi
          
          # Check for missing assets
          if [ -d "assets" ] && [ ! -f "assets/avatar-default.png" ]; then
            # Create a placeholder avatar
            mkdir -p assets
            echo "placeholder" > assets/avatar-default.png
            FIXED=true
            FIX_MESSAGE="${FIX_MESSAGE}\nAdded missing avatar placeholder"
          fi
          
          echo "FIXED=$FIXED" >> $GITHUB_OUTPUT
          echo "FIX_MESSAGE=$FIX_MESSAGE" >> $GITHUB_OUTPUT
          
      - name: Create Fix Commit
        if: steps.auto-fix.outputs.FIXED == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "🔧 Auto-fix deployment issues
          
          ${{ steps.auto-fix.outputs.FIX_MESSAGE }}
          
          Fixes #${{ steps.create-issue.outputs.result }}"
          
      - name: Push Fix
        if: steps.auto-fix.outputs.FIXED == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Close Issue if Fixed
        if: steps.auto-fix.outputs.FIXED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.create-issue.outputs.result }},
              state: 'closed',
              body: `## Deployment Error Report
            
            The deployment workflow failed but has been automatically fixed!
            
            ### Fix Applied
            ${{ steps.auto-fix.outputs.FIX_MESSAGE }}
            
            The issue has been resolved and the deployment should succeed on the next run.
            
            ---
            *Automatically fixed by Error Monitor workflow*`
            });
            
      - name: Comment on Issue if Not Fixed
        if: steps.auto-fix.outputs.FIXED != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: ${{ steps.create-issue.outputs.result }},
              body: `## Manual Intervention Required
            
            The automated fix system could not resolve this issue automatically.
            Please review the error logs and fix manually.
            
            Common things to check:
            - GitHub Pages settings
            - File permissions
            - Module import paths
            - Missing dependencies
            
            ---
            *Error Monitor workflow*`
            });